jobs:
  deploy-preview:
    name: Deploy preview site
    runs-on: ubuntu-latest
    environment:
      name: netlify
      url: ${{ vars.PREVIEW_URL }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Deploy preview site
        id: deploy_preview
        uses: ./
        with:
          auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site: ${{ vars.NETLIFY_SITE_NAME }}
          dir: sites/preview
          alias: preview
