- name: Vitest Badge Action
  # You may pin to the exact commit or the version.
  # uses: wjervis7/vitest-badge-action@df6e1406f1da38269a4313963b16d699362ce7dc
  uses: wjervis7/vitest-badge-action@v1.0.0
  with:
    # Type of result to make badge for. Can be 'lines', 'statements', 'functions', or 'branches'.
    result-type: 
    # Indicate if badge should be uploaded to Gist.
    upload-badge: # optional, default is true
    # Path to save the temporary badge to.
    badge-path: # optional, default is badge.svg
    # PAT for writing to gist.
    gist-token: # optional
    # Url to Gist.
    gist-url: # optional
    # Path to the vitest config file.
    vitest-config-path: # optional, default is vitest.config.ts
    # Path to the json summary file.
    summary-path: # optional, default is ./coverage/coverage-summary.json
    # Text to display on badge.
    badge-text: # optional, default is Tests
    # An array (comma separated) with hex (without #) or named colors of the badge value background, when coverage is at or above the threshold. More than one creates gradient background.
    badge-pass-color: # optional, default is 31c653
    # An array (comma separated) with hex (without #) or named colors of the badge value background, when coverage is below the threshold. More than one creates gradient background.
    badge-fail-color: # optional, default is 800000
    # An array (comma separated) with hex (without #) or named colors of the badge value background, when coverage results were not found. More than one creates gradient background.
    badge-neutral-color: # optional, default is 696969
